Let tests run correctly with ant 1.9.3.
Recent versions of ant pull in their own junit libraries,
and this seems to cause conflict with the junit used by battlecode's
tests.

This results in the following error after runing 'ant junit'

java.lang.NoClassDefFoundError: junit/framework/JUnit4TestAdapterCache

This has been noticed in other repositories:

https://github.com/real-logic/simple-binary-encoding/issues/96/

The simplest solution is to fork the test vm, which prevents the
invalid version of ant from being brought in.